########################################################################
# Dockerfile without BUILD_ARG
########################################################################

FROM alpine:latest

CMD ["/bin/echo", "Hello,", "world!"]

# vim:syntax=dockerfile:ai:sw=4:ts=4
