########################################################################
# Dockerfile for a Flask & Redis application
########################################################################

FROM shed/flask_base

MAINTAINER Joan Ordinas <jordinas@escoladeltreball.org>

COPY app.py /app/

# vim:syntax=dockerfile:ai:sw=4:ts=4
