########################################################################
# Dockerfile for htop
########################################################################

FROM alpine:latest

RUN apk add --update htop && rm -rf /var/cache/apk/*

CMD ["htop"]

# vim:syntax=dockerfile:ai:sw=4:ts=4
